[versions]
java = "25" # Don't forget to update *.mixins.json
kotlin = "2.3.0"
optigui = "2.3.0-beta.10+26.1"
minecraft = "26.1"
fabric-loom = "1.15-SNAPSHOT"
fabric-loader = "0.18.5"
fabric-language-kotlin = "1.13.8+kotlin.2.3.0"
commons-text = "1.12.0"
ini4j = "0.5.4"
dokka = "2.2.0"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-language-kotlin = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "fabric-language-kotlin" }
apache-commons-text = { group = "org.apache.commons", name = "commons-text", version.ref = "commons-text" }
ini4j = { group = "org.ini4j", name = "ini4j", version.ref = "ini4j" }
dokka-base = { group = "org.jetbrains.dokka", name = "dokka-base", version.ref = "dokka" }
dokka-plugin-java-syntax = { group = "org.jetbrains.dokka", name = "kotlin-as-java-plugin", version.ref = "dokka" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
