name: Report a crash
description: Open an issue about OptiGUI crashing
title: "[CRASH] <title>"
labels:
  - crash
body:
  - type: markdown
    attributes:
      value: |
        Please search existing issues to see if the crash you encountered has already been reported.
  - type: input
    attributes:
      label: Loader and its version
      description: Enter the loader and its version you are using
      placeholder: ex. Fabric loader 0.14.21
    validations:
      required: true
  - type: input
    attributes:
      label: OptiGUI version
      description: Enter the version of OptiGUI you are using
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Describe what you were doing before OptiGUI crashed
    validations:
      required: true
  - type: textarea
    attributes:
      label: Game logs
      description: Paste the game logs or a link to the uploaded logs here
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else
      description: Any additional information should be written here (optional)
    validations:
      required: false
