@file: JvmName("InteractionUtil")

package opekope2.optigui.util

import net.minecraft.nbt.NbtCompound
import opekope2.optigui.interaction.BlockInteractionData
import opekope2.optigui.interaction.EntityInteractionData
import opekope2.optigui.interaction.InteractionManager

/**
 * Creates an OptiGUI INI from the current interaction data.
 */
// TODO
fun inspectInteraction(): String? {
    val data = InteractionManager.interactionData ?: return null

    return buildString {
        appendLine("# Generated by OptiGUI Inspector")
        appendLine()

        appendLine("# You may not need all selectors")
        appendLine("[${data.id}]")
        /*for ((selectorKey, selector) in SelectorRegistry) {
            val selectorValue = selector.getRawSelector(interaction) ?: continue
            appendLine("$selectorKey=$selectorValue")
        }*/
        appendLine()

        when {
            data is BlockInteractionData && data.blockEntity != null -> {
                appendLine("# NBT (for more detailed inspection purposes, as there is no selector for NBT):")
                appendLine("# ${data.blockEntity.createNbt(data.world.registryManager)}")
                appendLine()
            }

            data is EntityInteractionData -> {
                appendLine("# NBT (for more detailed inspection purposes, as there is no selector for NBT):")
                appendLine("# ${data.entity.writeNbt(NbtCompound())}")
                appendLine()
            }

            else -> {
                appendLine("# NBT is not available")
                appendLine()
            }
        }

        appendLine("# If you have an idea or feedback about the inspector, feel free to share it at")
        appendLine("# https://github.com/opekope2/OptiGUI/issues/72")
    }
}
