name: Build project

on:
  workflow_call:
    inputs:
      test-project:
        type: boolean
      upload-output:
        type: boolean

jobs:
  build:
    name: Build project
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4.4.3
      - name: Load java version
        id: load-java-version
        uses: SebRollen/toml-action@v1.2.0
        with:
          file: gradle/libs.versions.toml
          field: versions.java
      - name: JDK setup
        uses: actions/setup-java@v4.7.1
        with:
          java-version: ${{ steps.load-java-version.outputs.value }}
          distribution: temurin
      - name: Build project
        run: ./gradlew build -x test
      - name: Test project
        if: inputs.test-project
        run: ./gradlew test
      - name: Upload build output
        if: inputs.upload-output && matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: jars
          path: OptiGUI/build/libs/*.jar
          if-no-files-found: error
